export type EnglishLevel = "beginner" | "intermediate" | "advanced";

export interface VocabularyItem {
  word: string;
  meaning: string;
  example?: string;
}

export interface PracticeQuestion {
  /** Optional question type for practice questions generated by AI. */
  type?: "grammar" | "vocabulary" | "comprehension";
  question: string;
  options: string[];
  correctIndex: number;
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  videoUrl: string;
  /** URL to a thumbnail image for the video (e.g. for profile grids). */
  thumbnailUrl?: string;
  level: EnglishLevel;
  durationSeconds: number;
  vocabulary?: VocabularyItem[];
  /** URL to a JSON file with segments (id, start, end, text). When absent, no subtitles are shown. */
  subtitlesUrl?: string;
  /** Topic category for preference scoring (e.g. grammar, pronunciation). */
  topic?: string;
  /** Free-form tags (e.g. vocabulary, grammar, phrasalverbs). */
  tags?: string[];
  /** Practice quiz questions for this lesson. */
  practice?: PracticeQuestion[];
  /**
   * Pre-generated sentences (4–10 words, clean punctuation) that are ideal
   * for pronunciation practice. Generated once from the transcript and stored
   * with the lesson.
   */
  practiceSentences?: string[];
}
